### ISSUE TITLE
staticman

### ISSUE THREAD

**Issue by badsyntax** [wetty/www.wetterer.de#6]
Hi There. I see you've invited @staticman-commenter to collaborate on this project. Unfortunately that account is used by me for my site and won't be able to be used for other projects.

**Comment by VincentTam** [comment]
Staticman's maintainer recommends using self-hosted Staticman instance in eduardoboucas/staticman<span>#</span>317:

> This has been resolved with <span>#</span>319. We are dropping support for the public Staticman instance and are recommending that all users host their own instance. The simplest way to do this is to click the "Deploy to Heroku" button in the README which will allow you to host your own instance for free without the reliability concerns of using a singular public instance. **The public instance will remain running for the time being, though I strongly recommend everyone move away from it.**

For a setup guide, you may see hajekj.net/2020/04/15/staticman-setup-in-app-service/, which inspired my illustrated guide: https://github.com/pacollins/hugo-future-imperfect-slim/wiki/staticman.yml.

Successful examples: mlsdpk/mlsdpk.github.io<span>#</span>2, VincentTam/beautiful-jekyll<span>#</span>35

**Comment by VincentTam** [comment]
@badsyntax If you keep using Staticman v2, you might want to close the `/v2/connect` route so that others can no longer invite <span>@</span>staticman-commenter:
https://www.gabescode.com/staticman/2019/01/03/create-staticman-instance.html#keep-other-people-out

However, the recently updated docs recommend using a private GitHub App with v3, so that others can make use of it:
https://staticman.net/docs/getting-started.html
